# Generated by Django 2.2.7 on 2019-12-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epirecipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dish_image',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='procedure',
            field=models.TextField(max_length=2000),
        ),
    ]
