# Generated by Django 2.2.7 on 2019-12-13 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epirecipe', '0004_auto_20191206_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
