# Generated by Django 2.2.7 on 2019-12-17 09:26

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('epirecipe', '0007_auto_20191216_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='procedure',
            field=tinymce.models.HTMLField(),
        ),
    ]
